### ISSUE TITLE
Delete Board.java

### ISSUE THREAD

**Issue by kernohad** [Dcbaas/Monopoly-Project-CIS350-G3#10]
We think the only thing this class will hold is an array of boardSquares. This can just be handled in the Game class.

**Comment by quirogas** [comment]
I think this is partially true. What if the game class only handles methods from its parts rather than logic ? What I'm thinking is that the board class will have squares, players, both decks of cards , and will be held responsible for moving the players between the squares and giving cards to the specific player.

**Comment by kernohad** [comment]
We were not sure if that would be handled in the Game class or not. Isnt the Game class in the Model, responsible for most logic?

**Comment by kernohad** [comment]
What all would be in the Game class then? Setting up the board (either class or data structure), ... what else? Isn't this where main logic goes? Dice roll function, selection functions, conditionals, etc?

**Comment by quirogas** [comment]
the board will do request for the bank, handle the dice, handle the trade class for the players, handle turns, and all request form one entity to another. Eg player roll a 4, game tells board to move player 4 spots, then game asks board for the corresponding boar square the player landed on. From then the game calls bank to sell/auction property. Player pays to bank (we need some discuss onto the best way to handle this)...some other player turn related stuff, but player finally ends turn. then game class gives the dice to the next player.

**Comment by kernohad** [comment]
I am closing this issue. After some discussion, we said it will be best to keep Board Class to keep track of cross communication between classes. We will discuss overall class design later.
