### ISSUE TITLE
Player rolling doubles

### ISSUE THREAD

**Issue by kernohad** [Dcbaas/Monopoly-Project-CIS350-G3#204]
- Currently, if the player rolls doubles, it moves them, but does not allow them to buy the property.
- Maybe this is how it is supposed to be? If so, lets make sure to disable the buy button (set canBuy to false or something) if they roll doubles

**Comment by Dcbaas** [comment]
Even when rolling doubles the player should be able to buy the property they first land on and any property on the second roll. Is the button enabled when they land on the first property?

**Comment by kernohad** [comment]
I am not sure if it is enabled on the first property. I dont think it is. 

We need to address all the canBuy logic and make sure its all good.

**Comment by Dcbaas** [comment]
That would be something for @kernohad  or @quirogas  to do cause you two know about that specific logic better than I do.

**Comment by kernohad** [comment]
Thats fine. I can try to look into it later tonight after I get some of this paper done. @Dcbaas, take a look at any issues you think pertain to code you wrote. There was a few token ones. And New Game/GUI resetting logic
